"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { api } from "@/lib/api";
import type { ReportData, AiPoint, KpiCard, DiseaseRow } from "@/lib/types";

function RagBadge({ rag }: { rag: string }) {
  const map: Record<string, string> = {
    green: "bg-bfe-green text-white",
    amber: "bg-bfe-amber text-white",
    red: "bg-bfe-red text-white",
    none: "bg-gray-200 text-gray-600",
  };
  return <span className={`inline-block w-3 h-3 rounded-full ${map[rag] ?? map.none}`} />;
}

function KpiCardEl({ kpi }: { kpi: KpiCard }) {
  const ragBorder: Record<string, string> = {
    green: "border-l-4 border-bfe-green",
    amber: "border-l-4 border-bfe-amber",
    red: "border-l-4 border-bfe-red",
    none: "border-l-4 border-gray-200",
  };
  const deltaColour = kpi.vs_prior_year === null ? "" :
    (kpi.higher_is_better ? (kpi.vs_prior_year > 0 ? "text-bfe-green" : "text-bfe-red") :
                             (kpi.vs_prior_year > 0 ? "text-bfe-red" : "text-bfe-green"));

  return (
    <div className={`card ${ragBorder[kpi.rag]}`}>
      <div className="flex items-start justify-between">
        <div className="text-xs text-gray-500 font-medium">{kpi.label}</div>
        <RagBadge rag={kpi.rag} />
      </div>
      <div className="text-2xl font-black mt-1">
        {kpi.value !== null ? `${kpi.value}${kpi.unit === "%" ? "%" : ""}` : "—"}
        {kpi.unit !== "%" && kpi.value !== null && (
          <span className="text-sm font-normal text-gray-400 ml-1">{kpi.unit}</span>
        )}
      </div>
      {kpi.vs_prior_year_label && (
        <div className={`text-xs mt-1 ${deltaColour}`}>{kpi.vs_prior_year_label}</div>
      )}
    </div>
  );
}

function AiPointCard({ point }: { point: AiPoint }) {
  const styles: Record<string, string> = {
    alert: "border-red-300 bg-red-50",
    warning: "border-amber-300 bg-amber-50",
    info: "border-blue-200 bg-blue-50",
  };
  const icons: Record<string, string> = { alert: "🔴", warning: "🟡", info: "🔵" };
  return (
    <div className={`rounded-xl border p-4 ${styles[point.severity]}`}>
      <div className="font-bold text-sm mb-1">{icons[point.severity]} {point.heading}</div>
      <p className="text-sm text-gray-700 leading-relaxed">{point.body}</p>
    </div>
  );
}

export default function ReportPage() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<ReportData | null>(null);
  const [aiPoints, setAiPoints] = useState<AiPoint[] | null>(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.getReport(id).then((d) => {
      setReport(d as ReportData);
      setLoading(false);
    });
  }, [id]);

  const handleGenerateBriefing = async () => {
    setAiLoading(true);
    const briefing = await api.getAiBriefing(id) as { points: AiPoint[] };
    setAiPoints(briefing.points);
    setAiLoading(false);
  };

  if (loading) {
    return <div className="flex items-center justify-center py-24 text-gray-400">Loading report…</div>;
  }
  if (!report) return null;

  return (
    <div className="max-w-3xl mx-auto px-5 py-6">
      {/* Action bar */}
      <div className="flex items-center gap-3 mb-6 no-print">
        <Link href="/admin" className="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1">
          ← Dashboard
        </Link>
        <div className="flex-1" />
        <button onClick={() => window.print()} className="btn-secondary text-sm py-2 px-4">
          Print / Save PDF
        </button>
      </div>

      {/* Farm header */}
      <div className="card mb-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-xl font-bold">{report.farm.name}</h1>
            <div className="text-sm text-gray-500">{report.farm.client_ref} · {report.period_label}</div>
            {report.farm.sbi_no && <div className="text-xs text-gray-400 mt-0.5">SBI: {report.farm.sbi_no}</div>}
          </div>
          <div className="flex flex-wrap gap-1 justify-end">
            {report.farm.enterprise_types.map((e) => (
              <span key={e} className="text-xs font-semibold px-2 py-1 rounded-full bg-bfe-purple-light text-bfe-purple">
                {e.replace("_", " ")}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* AI Briefing */}
      <div className="card mb-6">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h2 className="font-bold">AI Pre-Visit Briefing</h2>
            <p className="text-xs text-gray-500">Generated by analysing this farm&apos;s data. Use as a prompt — not a diagnosis.</p>
          </div>
          {aiPoints === null && !aiLoading && (
            <button onClick={handleGenerateBriefing} className="btn-primary text-sm py-2 px-4 no-print">
              Generate briefing
            </button>
          )}
          {aiLoading && (
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <div className="w-4 h-4 border-2 border-bfe-purple border-t-transparent rounded-full animate-spin" />
              Analysing…
            </div>
          )}
        </div>
        {aiPoints && (
          <div className="space-y-3">
            {aiPoints.map((p, i) => <AiPointCard key={i} point={p} />)}
          </div>
        )}
      </div>

      {/* Sheep KPIs */}
      {report.sheep_kpis.length > 0 && (
        <section className="mb-6">
          <h2 className="font-bold text-gray-700 mb-3">🐑 Sheep Performance</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {report.sheep_kpis.map((kpi) => <KpiCardEl key={kpi.key} kpi={kpi} />)}
          </div>
        </section>
      )}

      {/* Suckler KPIs */}
      {report.suckler_kpis.length > 0 && (
        <section className="mb-6">
          <h2 className="font-bold text-gray-700 mb-3">🐄 Suckler Performance</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {report.suckler_kpis.map((kpi) => <KpiCardEl key={kpi.key} kpi={kpi} />)}
          </div>
        </section>
      )}

      {/* Disease log */}
      {report.diseases.length > 0 && (
        <section className="card mb-6">
          <h2 className="font-bold mb-3">Disease Case Log</h2>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-gray-400 border-b border-gray-100">
                <th className="pb-2 font-semibold">Condition</th>
                <th className="pb-2 font-semibold text-right">This year</th>
                <th className="pb-2 font-semibold text-right">Prior year</th>
                <th className="pb-2 font-semibold text-right">Change</th>
              </tr>
            </thead>
            <tbody>
              {report.diseases.map((d: DiseaseRow) => {
                const delta = d.this_year - d.prior_year;
                return (
                  <tr key={d.condition} className="border-b border-gray-50 last:border-0">
                    <td className="py-2 font-medium">{d.condition}</td>
                    <td className="py-2 text-right">{d.this_year}</td>
                    <td className="py-2 text-right text-gray-400">{d.prior_year}</td>
                    <td className={`py-2 text-right font-semibold ${delta > 0 ? "text-bfe-red" : delta < 0 ? "text-bfe-green" : "text-gray-400"}`}>
                      {delta > 0 ? `+${delta}` : delta}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>
      )}

      {/* Farmer notes */}
      {(report.farmer_notes.went_well || report.farmer_notes.challenges || report.farmer_notes.targets) && (
        <section className="card mb-6">
          <h2 className="font-bold mb-3">Farmer Notes</h2>
          <div className="space-y-3 text-sm text-gray-600">
            {report.farmer_notes.went_well && (
              <div><span className="font-semibold text-bfe-green">What went well: </span>{report.farmer_notes.went_well}</div>
            )}
            {report.farmer_notes.challenges && (
              <div><span className="font-semibold text-bfe-amber">Challenges: </span>{report.farmer_notes.challenges}</div>
            )}
            {report.farmer_notes.targets && (
              <div><span className="font-semibold text-bfe-purple">Targets: </span>{report.farmer_notes.targets}</div>
            )}
          </div>
        </section>
      )}

      {/* Vet notes */}
      <section className="card no-print">
        <h2 className="font-bold mb-2">Vet Notes</h2>
        <textarea
          className="w-full border border-gray-200 rounded-xl p-3 text-sm focus:outline-none focus:border-bfe-purple resize-none"
          rows={4}
          placeholder="Add notes for this visit…"
        />
      </section>

      <div className="text-center text-xs text-gray-400 mt-8 no-print">
        Belmont Farm &amp; Equine Vets · Farm Health Programme · Confidential
      </div>
    </div>
  );
}
